# 部署 VitePress 站点到 GitHub Pages 的工作流配置
# 该工作流会在推送到 master 分支时自动触发，也支持手动触发
name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    types: [labeled]

# 配置工作流所需的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 配置并发执行策略
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24 # 使用 Node  24
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build with VitePress
        run: pnpm build # 执行 package.json 中的构建脚本
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist # 上传构建好的静态文件
