name: Deploy VitePress site to Pages

on:
  push:
    branches: [master] # 推送到 master 分支时触发
  workflow_dispatch: # 允许手动触发

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24 # 使用 Node  24
          cache: pnpm # 使用 pnpm
      - name: Install PNPM
        run: npm install pnpm -g
      - name: Install dependencies
        run: pnpm install
      - name: Build with VitePress
        run: pnpm build # 执行 package.json 中的构建脚本
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist # 上传构建好的静态文件

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4